export const SUBMIT_DEPLOYMENT = 'SUBMIT_DEPLOYMENT';
export const GET_DEPLOYMENTS = 'GET_DEPLOYMENTS';
export const DELETE_DEPLOYMENT = 'DELETE_DEPLOYMENT';
export const GET_TEMPLATE = 'GET_TEMPLATE';